import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';

const root = existsSync('extension') ? '.' : 'v3';
const allowedFiles = new Set([
    'README.md',
    'nox-v3.sh',
    'extension/extension.js',
    'extension/metadata.json',
    'extension/prefs.js',
    'extension/stylesheet.css',
    'extension/schemas/org.gnome.shell.extensions.nox-v3.gschema.xml',
    'extension/assets/nox/walk/0.webp',
    'extension/assets/nox/walk/1.webp',
    'extension/assets/nox/walk/2.webp',
    'extension/assets/nox/walk/3.webp',
    'extension/assets/nox/walk/4.webp',
    'extension/assets/nox/walk/5.webp',
    'extension/assets/nox/walk/6.webp',
    'extension/assets/nox/walk/7.webp',
    'extension/assets/nox/walk/8.webp',
    'extension/assets/nox/walk/9.webp',
    'extension/assets/nox/walk/10.webp',
    'extension/assets/nox/walk/11.webp',
    'extension/assets/nox/walk/12.webp',
    'extension/assets/nox/walk/13.webp',
    'extension/assets/nox/walk/14.webp',
    'extension/assets/nox/walk/15.webp',
    'extension/assets/nox/rest/0.webp',
    'extension/assets/nox/rest/1.webp',
    'extension/assets/nox/rest/2.webp',
    'extension/assets/nox/rest/3.webp',
    'extension/assets/nox/rest/4.webp',
    'extension/assets/nox/rest/5.webp',
    'extension/assets/nox/rest/6.webp',
    'extension/assets/nox/rest/7.webp',
    'extension/assets/nox/rest/8.webp',
    'extension/assets/nox/rest/9.webp',
    'extension/assets/nox/rest/10.webp',
    'extension/assets/nox/rest/11.webp',
    'extension/assets/nox/rest/12.webp',
    'extension/assets/nox/rest/13.webp',
    'extension/assets/nox/rest/14.webp',
    'extension/assets/nox/rest/15.webp',
    'extension/assets/nox/rest/16.webp',
    'extension/assets/nox/rest/17.webp',
    'extension/assets/nox/rest/18.webp',
    'extension/assets/nox/rest/19.webp',
    'extension/assets/nox/rest/20.webp',
    'extension/assets/nox/rest/21.webp',
    'extension/assets/nox/rest/22.webp',
    'extension/assets/nox/rest/23.webp',
    'extension/assets/nox/rest/24.webp',
    'extension/assets/nox/rest/25.webp',
    'extension/assets/nox/rest/26.webp',
    'extension/assets/nox/rest/27.webp',
    'extension/assets/nox/rest/28.webp',
    'extension/assets/nox/rest/29.webp',
    'extension/assets/nox/rest/30.webp',
    'extension/assets/nox/rest/31.webp',
    'extension/assets/nox/rest/32.webp',
    'extension/assets/nox/rest/33.webp',
    'extension/assets/nox/rest-profile/0.webp',
    'extension/assets/nox/rest-profile/1.webp',
    'extension/assets/nox/rest-profile/2.webp',
    'extension/assets/nox/rest-profile/3.webp',
    'extension/assets/nox/rest-profile/4.webp',
    'extension/assets/nox/rest-profile/5.webp',
    'extension/assets/nox/rest-profile/6.webp',
    'extension/assets/nox/rest-profile/7.webp',
    'extension/assets/nox/rest-profile/8.webp',
    'extension/assets/nox/rest-profile/9.webp',
    'extension/assets/nox/rest-profile/10.webp',
    'extension/assets/nox/rest-profile/11.webp',
    'extension/assets/nox/rest-profile/12.webp',
    'extension/assets/nox/rest-profile/13.webp',
    'extension/assets/nox/rest-profile/14.webp',
    'extension/assets/nox/rest-profile/15.webp',
    'extension/assets/nox/rest-profile/16.webp',
    'extension/assets/nox/rest-profile/17.webp',
    'extension/assets/nox/rest-profile/18.webp',
    'extension/assets/nox/rest-profile/19.webp',
    'extension/assets/nox/rest-profile/20.webp',
    'extension/assets/nox/rest-profile/21.webp',
    'extension/assets/nox/rest-profile/22.webp',
    'extension/assets/nox/rest-profile/23.webp',
    'extension/assets/nox/rest-profile/24.webp',
    'extension/assets/nox/rest-profile/25.webp',
    'extension/assets/nox/rest-profile/26.webp',
    'extension/assets/nox/rest-profile/27.webp',
    'extension/assets/nox/rest-profile/28.webp',
    'extension/assets/nox/rest-profile/29.webp',
    'extension/assets/nox/rest-profile/30.webp',
    'extension/assets/nox/rest-profile/31.webp',
    'extension/assets/nox/rest-profile/32.webp',
    'extension/assets/nox/rest-profile/33.webp',
    'extension/assets/nox/rest-profile/34.webp',
    'extension/assets/nox/rest-profile/35.webp',
    'extension/assets/nox/rest-profile/36.webp',
    'extension/assets/nox/rest-profile/37.webp',
    'extension/assets/nox/rest-profile/38.webp',
    'extension/assets/nox/rest-profile/39.webp',
    'extension/assets/nox/rest-profile/40.webp',
    'extension/assets/nox/rest-profile/41.webp',
    'extension/assets/nox/rest-profile/42.webp',
    'extension/assets/nox/rest-profile/43.webp',
    'extension/assets/nox/rest-profile/44.webp',
    'extension/assets/nox/rest-profile/45.webp',
    'extension/assets/nox/rest-profile/46.webp',
    'extension/assets/nox/rest-profile/47.webp',
    'extension/assets/nox/rest-profile/48.webp',
    'extension/assets/nox/rest-profile/49.webp',
    'extension/assets/nox/rest-profile/50.webp',
    'extension/assets/nox/rest-profile/51.webp',
    'extension/assets/nox/rest-profile/52.webp',
    'extension/assets/nox/rest-profile/53.webp',
    'extension/assets/nox/rest-profile-cropped/0.webp',
    'extension/assets/nox/rest-profile-cropped/1.webp',
    'extension/assets/nox/rest-profile-cropped/2.webp',
    'extension/assets/nox/rest-profile-cropped/3.webp',
    'extension/assets/nox/rest-profile-cropped/4.webp',
    'extension/assets/nox/rest-profile-cropped/5.webp',
    'extension/assets/nox/rest-profile-cropped/6.webp',
    'extension/assets/nox/rest-profile-cropped/7.webp',
    'extension/assets/nox/rest-profile-cropped/8.webp',
    'extension/assets/nox/rest-profile-cropped/9.webp',
    'extension/assets/nox/rest-profile-cropped/10.webp',
    'extension/assets/nox/rest-profile-cropped/11.webp',
    'extension/assets/nox/rest-profile-cropped/12.webp',
    'extension/assets/nox/rest-profile-cropped/13.webp',
    'extension/assets/nox/rest-profile-cropped/14.webp',
    'extension/assets/nox/rest-profile-cropped/15.webp',
    'extension/assets/nox/rest-profile-cropped/16.webp',
    'extension/assets/nox/rest-profile-cropped/17.webp',
    'extension/assets/nox/rest-profile-cropped/18.webp',
    'extension/assets/nox/rest-profile-cropped/19.webp',
    'extension/assets/nox/rest-profile-cropped/20.webp',
    'extension/assets/nox/rest-profile-cropped/21.webp',
    'extension/assets/nox/rest-profile-cropped/22.webp',
    'extension/assets/nox/rest-profile-cropped/23.webp',
    'extension/assets/nox/rest-profile-cropped/24.webp',
    'extension/assets/nox/rest-profile-cropped/25.webp',
    'extension/assets/nox/rest-profile-cropped/26.webp',
    'extension/assets/nox/rest-profile-cropped/27.webp',
    'extension/assets/nox/rest-profile-cropped/28.webp',
    'extension/assets/nox/rest-profile-cropped/29.webp',
    'extension/assets/nox/rest-profile-cropped/30.webp',
    'extension/assets/nox/rest-profile-cropped/31.webp',
    'extension/assets/nox/rest-profile-cropped/32.webp',
    'extension/assets/nox/rest-profile-cropped/33.webp',
    'extension/assets/nox/rest-profile-cropped/34.webp',
    'extension/assets/nox/rest-profile-cropped/35.webp',
    'extension/assets/nox/rest-profile-cropped/36.webp',
    'extension/assets/nox/rest-profile-cropped/37.webp',
    'extension/assets/nox/rest-profile-cropped/38.webp',
    'extension/assets/nox/rest-profile-cropped/39.webp',
    'extension/assets/nox/rest-profile-cropped/40.webp',
    'extension/assets/nox/rest-profile-cropped/41.webp',
    'extension/assets/nox/rest-profile-cropped/42.webp',
    'extension/assets/nox/rest-profile-cropped/43.webp',
    'extension/assets/nox/rest-profile-cropped/44.webp',
    'extension/assets/nox/rest-profile-cropped/45.webp',
    'extension/assets/nox/rest-profile-cropped/46.webp',
    'extension/assets/nox/rest-profile-cropped/47.webp',
    'extension/assets/nox/rest-profile-cropped/48.webp',
    'extension/assets/nox/rest-profile-cropped/49.webp',
    'extension/assets/nox/rest-profile-cropped/50.webp',
    'extension/assets/nox/rest-profile-cropped/51.webp',
    'extension/assets/nox/rest-profile-cropped/52.webp',
    'extension/assets/nox/rest-profile-cropped/53.webp',
    'extension/src/animation/catalog.js',
    'extension/src/animation/playback.js',
    'extension/src/actions/flip-at-wall.js',
    'extension/src/actions/lifecycle.js',
    'extension/src/actions/run.js',
    'extension/src/actions/walk.js',
    'extension/src/actor.js',
    'extension/src/behavior/conditions.js',
    'extension/src/behavior/registry.js',
    'extension/src/behavior/selector.js',
    'extension/src/behavior/tree.js',
    'extension/src/core/action-state.js',
    'extension/src/core/body.js',
    'extension/src/core/constants.js',
    'extension/src/core/context.js',
    'extension/src/core/drag-drop.js',
    'extension/src/core/drag-tracker.js',
    'extension/src/core/controller.js',
    'extension/src/core/geometry.js',
    'extension/src/core/locomotion.js',
    'extension/src/core/physics.js',
    'extension/src/core/types.js',
    'extension/src/shell/windows.js',
    'extension/src/config/movement-profiles.js',
    'extension/src/config/gravity-profiles.js',
    'extension/src/config/settings.js',
    'extension/src/connection/frames.js',
    'extension/src/connection/settings.js',
    'extension/src/connection/transport.js',
    'extension/src/connection/visual.js',
    'extension/src/message/bubble.js',
    'extension/src/message/movement-modifier.js',
    'extension/src/message/queue.js',
    'extension/src/world/edge.js',
    'extension/src/world/occlusion.js',
    'extension/src/world/screen.js',
    'extension/src/world/support.js',
    'extension/src/world/surface.js',
    'extension/src/world/world.js',
    'extension/assets/nox/run/0.webp',
    'extension/assets/nox/run/1.webp',
    'extension/assets/nox/run/2.webp',
    'extension/assets/nox/run/3.webp',
    'extension/assets/nox/run/4.webp',
    'extension/assets/nox/run/5.webp',
    'extension/assets/nox/run/6.webp',
    'extension/assets/nox/run/7.webp',
    'extension/assets/nox/run/8.webp',
    'extension/assets/nox/run/9.webp',
    'extension/assets/nox/run/10.webp',
    'extension/assets/nox/run/11.webp',
    'extension/assets/nox/run/12.webp',
    'extension/assets/nox/run/13.webp',
    'test/assets.test.mjs',
    'test/clean-folder.test.mjs',
    'test/config.test.mjs',
    'test/foundation.test.mjs',
    'test/install-script.test.mjs',
    'test/schema-prefs.test.mjs',
]);

const forbidden = [
    /nox@selfhosted\.local/i,
    /movement-v2/i,
    /MovementControllerV2/,
    /\btest panel\b/i,
    /\bjump\b/i,
    /\bsit\b/i,
    /\buturn\b/i,
    /\bu-turn\b/i,
    /\bjetpack\b/i,
    /\bwall-bang\b/i,
    /\bwallbang\b/i,
];

function files(dir) {
    const found = [];
    for (const name of readdirSync(dir)) {
        if (name === '.git')
            continue;
        const path = join(dir, name);
        if (statSync(path).isDirectory())
            found.push(...files(path));
        else
            found.push(relative(root, path));
    }
    return found.sort();
}

describe('clean V3 extension boundary', () => {
    it('contains only approved V3 files', () => {
        assert.deepEqual(files(root), [...allowedFiles].sort());
    });

    it('does not reference legacy feature systems', () => {
        const exempt = new Set([
            'test/clean-folder.test.mjs',
            'test/assets.test.mjs',
            'test/schema-prefs.test.mjs',
            'test/config.test.mjs',
            'test/foundation.test.mjs',
            'README.md',
        ]);
        for (const file of files(root)) {
            if (exempt.has(file) || file.endsWith('.webp'))
                continue;
            const text = readFileSync(join(root, file), 'utf8');
            for (const pattern of forbidden)
                assert.equal(pattern.test(text), false, `${file} references ${pattern}`);
        }
    });
});
